//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterthesisGHA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasterthesisGHA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2D_Truss_Icon {
            get {
                object obj = ResourceManager.GetObject("2D_Truss_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3D_Truss_Icon {
            get {
                object obj = ResourceManager.GetObject("3D_Truss_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap csvUltra {
            get {
                object obj = ResourceManager.GetObject("csvUltra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FCA {
            get {
                object obj = ResourceManager.GetObject("FCA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FrameFEA {
            get {
                object obj = ResourceManager.GetObject("FrameFEA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GH_icon1 {
            get {
                object obj = ResourceManager.GetObject("GH_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LCA {
            get {
                object obj = ResourceManager.GetObject("LCA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MaterialBank {
            get {
                object obj = ResourceManager.GetObject("MaterialBank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MaterialBank1 {
            get {
                object obj = ResourceManager.GetObject("MaterialBank1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPE80,764,801000,84890,6727
        ///IPE100,1032,1710000,159200,11530
        ///IPE120,1321,3180000,276700,16890
        ///IPE140,1643,5410000,449200,24010
        ///IPE160,2009,8690000,683100,35300
        ///IPE180,2395,13200000,1009000,47230
        ///IPE200,2848,19400000,1424000,68460
        ///IPE220,3337,27700000,2049000,89820
        ///IPE240,3912,38900000,2836000,127400
        ///IPE270,4595,57900000,4199000,157100
        ///IPE300,5381,83600000,6038000,197500
        ///IPE330,6261,117700000,7881000,275900
        ///IPE360,7273,162700000,10430000,370800
        ///IPE400,8446,231300000,13180000,504100
        ///IPE450,9882, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPE80,80,46,3.8,5.2,5,6,0.328,764,358,478,0.8014,32.4,20.03,23.22,0.08489,10.5,3.691,5.818,6.727,1.77,115.1,135.2
        ///IPE100,100,55,4.1,5.7,7,8.1,0.4,1032,508,627,1.71,40.7,34.2,39.41,0.1592,12.4,5.789,9.146,11.53,2.812,342.1,266.8
        ///IPE120,120,64,4.4,6.3,7,10.4,0.475,1321,631,806,3.178,49,52.96,60.73,0.2767,14.5,8.646,13.58,16.89,3.839,872,483.4
        ///IPE140,140,73,4.7,6.9,7,12.9,0.551,1643,764,1007,5.412,57.4,77.32,88.34,0.4492,16.5,12.31,19.25,24.01,5.109,1951,808.2
        ///IPE160,160,82,5,7.4,9,15.8,0.623,2009,966,1214 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProfilesAdvanced {
            get {
                return ResourceManager.GetString("ProfilesAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReuseALL {
            get {
                object obj = ResourceManager.GetObject("ReuseALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReuseBF {
            get {
                object obj = ResourceManager.GetObject("ReuseBF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReuseBnB {
            get {
                object obj = ResourceManager.GetObject("ReuseBnB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReuseHeuristics {
            get {
                object obj = ResourceManager.GetObject("ReuseHeuristics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TrussMSA {
            get {
                object obj = ResourceManager.GetObject("TrussMSA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Visuals {
            get {
                object obj = ResourceManager.GetObject("Visuals", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
